import type { Metadata } from 'next';
import { Fira_Mono } from 'next/font/google';

import '@/styles/global.scss';
import '@/styles/_variables.scss';
import { Providers } from './providers';

const inter = Fira_Mono({ subsets: ['cyrillic', 'latin'], weight: '400' });

export const metadata: Metadata = {
  title: {
    default: 'Quick',
    template: `Quick | %s`,
  },
  description: 'Generated by create next app',
  icons: '/icon-logo.svg',
};

// Определение цветовой темы до подгрузки страницы
const setInitialTheme = `
(function() {
  try {
    var color = localStorage.getItem('color') || 'purple';
    document.documentElement.setAttribute('data-color', color);

    var theme = localStorage.getItem('color-theme') || 'light';
    document.documentElement.setAttribute('data-theme', theme);
  } catch (_) {}
})();
`;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <head>
        <script dangerouslySetInnerHTML={{ __html: setInitialTheme }} />
      </head>
      <body className={inter.className}>
        <Providers>
          <main className='min-h-screen min-w-screen'>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
